-- Example for neo-tree.nvim
return {
  -- {
  --   's1n7ax/nvim-window-picker',
  --   name = 'window-picker',
  --   event = 'VeryLazy',
  --   version = '2.*',
  --   config = true,
  -- },
  -- {
  --   'nvim-neo-tree/neo-tree.nvim',
  --   branch = 'v3.x',
  --   dependencies = {
  --     'nvim-lua/plenary.nvim',
  --     'nvim-tree/nvim-web-devicons', -- not strictly required, but recommended
  --     'MunifTanjim/nui.nvim',
  --     -- '3rd/image.nvim', -- Optional image support in preview window: See `# Preview Mode` for more information
  --   },
  --   keys = {
  --     { '\\', '<cmd>Neotree reveal<CR>', desc = 'NeoTree reveal' },
  --     { '<leader>m', '<cmd>Neotree toggle<CR>', desc = 'Toggle NeoTree' },
  --     { '<leader>n', '<cmd>Neotree filesystem reveal left<CR>', desc = 'Find current file in NeoTree' },
  --     { '<leader>bf', '<cmd>Neotree buffers reveal float<CR>', desc = 'Show all recent opened files' },
  --   },
  --   config = function()
  --     require('neo-tree').setup({
  --       close_if_last_window = true, -- Close Neo-tree if it is the last window left in the tab
  --       popup_border_style = 'rounded',
  --       default_component_configs = {
  --         indent = {
  --           -- expander config, needed for nesting files
  --           with_expanders = true, -- if nil and file nesting is enabled, will enable expanders
  --           -- expander_collapsed = '',
  --           -- expander_expanded = '',
  --           expander_collapsed = '',  -- arrow when folder is closed
  --           expander_expanded = '',   -- arrow when folder is open
  --           expander_highlight = 'NeoTreeExpander',
  --         },
  --         icon = {
  --           -- folder_closed = '',
  --           -- folder_open = '',
  --           -- folder_empty = '󰜌',
  --         },
  --         modified = {
  --           symbol = '[+]',
  --           highlight = 'NeoTreeModified',
  --         },
  --         name = {
  --           trailing_slash = false,
  --           highlight_opened_files = true, -- Requires `enable_opened_markers = true`.
  --                                          -- Take values in { false (no highlight), true (only loaded),
  --                                          -- "all" (both loaded and unloaded)}. For more information,
  --                                          -- see the `show_unloaded` config of the `buffers` source.
  --           use_git_status_colors = true,
  --           highlight = 'NeoTreeFileName',
  --         },
  --         git_status = {
  --           symbols = {
  --             -- Change type
  --             added     = "✚", -- NOTE: you can set any of these to an empty string to not show them
  --             deleted   = "✖",
  --             modified  = "",
  --             renamed   = "󰁕",
  --             -- Status type
  --             untracked = "",
  --             ignored   = "",
  --             unstaged  = "󰄱",
  --             staged    = "",
  --             conflict  = "",
  --           },
  --           align = "right",
  --         },
  --       },
  --       window = {
  --         position = 'left',
  --         width = 40,
  --         mapping_options = {
  --           noremap = true,
  --           nowait = true,
  --         },
  --         mappings = {
  --           ['<space>'] = {
  --             'toggle_node',
  --             nowait = false, -- disable `nowait` if you have existing combos starting with this char that you want to use
  --           },
  --           ['<2-LeftMouse>'] = 'open',
  --           ['<cr>'] = 'open',
  --           -- ['<cr>'] = 'open_with_window_picker',
  --           ['<esc>'] = 'cancel', -- close preview or floating neo-tree window
  --           -- ['S'] = 'open_split',
  --           -- ['s'] = 'open_vsplit',
  --           ['S'] = 'split_with_window_picker',
  --           ['s'] = 'vsplit_with_window_picker',
  --           ['t'] = 'open_tabnew',
  --           -- ['<cr>'] = 'open_drop',
  --           -- ['t'] = 'open_tab_drop',
  --           ['w'] = 'open_with_window_picker',
  --           --['P'] = 'toggle_preview', -- enter preview mode, which shows the current node without focusing
  --         }
  --       },
  --       filesystem = {
  --         filtered_items = {
  --           visible = false, -- when true, they will just be displayed differently than normal items
  --           hide_dotfiles = true,
  --           hide_gitignored = true,
  --           hide_hidden = true, -- only works on Windows for hidden files/directories
  --           hide_by_name = {
  --             --'node_modules'
  --           },
  --           hide_by_pattern = { -- uses glob style patterns
  --             --'*.meta',
  --             --'*/src/*/tsconfig.json',
  --           },
  --           always_show = { -- remains visible even if other settings would normally hide it
  --             --'.gitignored',
  --           },
  --           never_show = { -- remains hidden even if visible is toggled to true, this overrides always_show
  --             --'.DS_Store',
  --             --'thumbs.db'
  --           },
  --           never_show_by_pattern = { -- uses glob style patterns
  --             --'.null-ls_*',
  --           },
  --         },
  --         follow_current_file = {
  --           enabled = false, -- This will find and focus the file in the active buffer every time
  --           --               -- the current file is changed while the tree is open.
  --           leave_dirs_open = false, -- `false` closes auto expanded dirs, such as with `:Neotree reveal`
  --         },
  --         hijack_netrw_behavior = 'open_default', -- netrw disabled, opening a directory opens neo-tree
  --       },
  --       buffers = {
  --         follow_current_file = {
  --           enabled = true, -- This will find and focus the file in the active buffer every time
  --           --              -- the current file is changed while the tree is open.
  --           leave_dirs_open = false, -- `false` closes auto expanded dirs, such as with `:Neotree reveal`
  --         },
  --         show_unloaded = true,
  --       },
  --     })
  --
  --     -- vim.keymap.set('n', '\\', ':Neotree reveal<CR>', {})
  --
  --     -- Change color for arrows in tree to light blue
  --     -- vim.cmd([[ highlight NvimTreeFolderArrowClosed guifg=#3FC5FF ]])
  --     vim.cmd([[ highlight NeoTreeExpander guifg=#3FC5FF ]])
  --   end
  -- }
}
