# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="/Users/alejandro.ventura/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="alexventuraio"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS=true

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git osx ruby rails bundler brew rake capistrano)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

#========== Customize to your needs...

# ***** Note *****
# If you are a rails developer and using RVM, make sure you have added the following line at the end of your .zshrc file.
# [[ -s “$HOME/.rvm/scripts/rvm” ]] && . “$HOME/.rvm/scripts/rvm”

# export PATH=/usr/local/bin:/Users/chris/.rvm/gems/ruby-1.9.3-p125/bin:/Users/chris/.rvm/gems/ruby-1.9.3-p125@global/bin:/Users/chris/.rvm/rubies/ruby-1.9.3-p125/bin:/Users/chris/.rvm/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin

#---------------------- Alejandro Ventura ----------------------

# Default editor
#export EDITOR="/Applications/Sublime\ Text.app/Contents/MacOS/Sublime\ Text"

alias cl='clear'
alias gpom='git push origin master'
alias gphm='git push heroku master'
alias rsb='rs -b 0.0.0.0'
alias rsp='rs -p 5000'
alias codi=vscodium

# To open a Gem source code
ogem () {
  EDITOR=mvim bundle open $@
}

# To open a folder content or file on Sublime Text
sub () {
  open -a "Sublime Text" $@
}

# Vagrant Provider
export VAGRANT_DEFAULT_PROVIDER=parallels

# Load ENV variables
#export AWS_ACCESS_KEY_ID=xxxxxxxxxxxxxxxx
#export AWS_SECRET_ACCESS_KEY=xxxxxxxxxxxxxxxx
#export AWS_S3_BUCKET=xxxxxxxxxxxxxxxx
#export AWS_REGION=xxxxxxxxxxxxxxxx
#export SENDGRID_API_KEY=xxxxxxxxxxxxxxxx
#export OPENPAY_MERCHANT_ID=xxxxxxxxxxxxxxxx
#export OPENPAY_PRIVATE_KEY=xxxxxxxxxxxxxxxx
#export MAILTRAP_USERNAME=xxxxxxxxxxxxxxxx
#export MAILTRAP_PASSWORD=xxxxxxxxxxxxxxxx

# NVM for Node manager version
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Calling nvm use automatically in a directory with a .nvmrc file
# place this after nvm initialization!
autoload -U add-zsh-hook
load-nvmrc() {
  local node_version="$(nvm version)"
  local nvmrc_path="$(nvm_find_nvmrc)"

  if [ -n "$nvmrc_path" ]; then
    local nvmrc_node_version=$(nvm version "$(cat "${nvmrc_path}")")

    if [ "$nvmrc_node_version" = "N/A" ]; then
      nvm install
    elif [ "$nvmrc_node_version" != "$node_version" ]; then
      nvm use
    fi
  elif [ "$node_version" != "$(nvm version default)" ]; then
    echo "Reverting to nvm default version"
    nvm use default
  fi
}
add-zsh-hook chpwd load-nvmrc
load-nvmrc

# To install Qt55 using the DMG file because Hombrew does not supports it anymore
# export PATH="/usr/local/opt/qt@5.5/bin:$PATH"
# export PATH="/Users/alex/Qt5.5.1/5.5/clang_64/bin:$PATH"

# Bullet-Train them for oh-my-zsh override config
BULLETTRAIN_PROMPT_ORDER=(
  time
  context
  dir
  ruby
  git
)

# To enable Syntax highlighting
# Install: git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

function fzf_then_open_in_editor() {
 local file=$(fzf)
 # Open the file if it exists
 if [ -n "$file" ]; then
   # Use the default editor if it's defined, otherwise mvim
   ${EDITOR:-vim} "$file"
 fi
}
# Execute the function using Ctrl+f('^f') | fn+F1(^[OP)
bindkey -s '^[OP' fzf_then_open_in_editor
